(SELECT NAME, CUSTOMERS_NUMBER
FROM LAWYERS
WHERE CUSTOMERS_NUMBER = (SELECT MAX(L.CUSTOMERS_NUMBER) FROM LAWYERS L)
)
UNION ALL
(SELECT NAME, CUSTOMERS_NUMBER
FROM LAWYERS
WHERE CUSTOMERS_NUMBER = (SELECT MIN(L.CUSTOMERS_NUMBER) FROM LAWYERS L)
)
UNION ALL
(SELECT 'Average' AS NAME, ROUND(AVG(CUSTOMERS_NUMBER), 0) AS CUSTOMERS_NUMBER
FROM LAWYERS
)