SELECT A.NAME, B.NAME, C.NAME
FROM PRODUCTS A
INNER JOIN PROVIDERS B ON B.ID = A.ID_PROVIDERS
INNER JOIN CATEGORIES C ON C.ID = A.ID_CATEGORIES
WHERE B.NAME LIKE '%Sansul SA%' AND C.NAME LIKE '%Imported%';